namespace RhoMicro.Staple.Analyzers;

using Microsoft.CodeAnalysis;
using CodeAnalysis.Lyra;

/// <summary>
/// Minimal incremental generator boilerplate.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class Generator : IIncrementalGenerator
{
    private static readonly CSharpSourceBuilderOptions _builderOptions = new()
    {
        Prelude = (w, _) => w.AppendLine(
            $"""
             // <auto-generated>
             // This file was generated using the {typeof(Generator)}.
             // </auto-generated>
             """)
    };

    /// <summary>
    /// Initializes the generator pipeline.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var sourceProvider = context.CompilationProvider
            .SelectMany(static (c, ct) =>
            {
                ct.ThrowIfCancellationRequested();

                var result = new List<(String id, String source)>();
                add(c.Assembly.GlobalNamespace);

                return result;

                void add(ISymbol member)
                {
                    if (!SymbolEqualityComparer.Default.Equals(member.ContainingAssembly, c.Assembly))
                    {
                        return;
                    }

                    if (member is INamespaceSymbol @namespace)
                    {
                        foreach (var m in @namespace.GetMembers())
                        {
                            ct.ThrowIfCancellationRequested();

                            add(m);
                        }

                        return;
                    }

                    var id = member.GetDocumentationCommentId();

                    if (id is [_, ..])
                    {
                        var source = member.GetDocumentationCommentXml(
                            preferredCulture: null,
                            expandIncludes: true,
                            ct);

                        if (source is [_, ..])
                        {
                            result.Add((id, source));
                        }
                    }

                    if (member is not ITypeSymbol type)
                    {
                        return;
                    }

                    foreach (var m in type.GetMembers())
                    {
                        ct.ThrowIfCancellationRequested();

                        add(m);
                    }
                }
            })
            .Collect()
            .Select(static (d, ct) =>
            {
                ct.ThrowIfCancellationRequested();
                var builder = new CSharpSourceBuilder(_builderOptions);

                foreach (var (id, source) in d)
                {
                    builder.AppendLine(
                        $""""
                         [assembly: {typeof(XmlDocumentationAttribute)}(
                            id: "{id}",
                            source: 
                                """
                                {source}
                                """)]
                         """");
                }

                var result = (hintName: "Documentation.g.cs", source: builder.ToString());

                return result;
            });

        context.RegisterSourceOutput(sourceProvider, static (c, t) => c.AddSource(t.hintName, t.source));
    }
}
