<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <DebugSymbols>false</DebugSymbols>
    <IncludeSymbols>false</IncludeSymbols>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>RhoMicro.Staple.Analyzers</PackageId>
    <Description>This package provides a generator for attaching documentation in metadata via assembly attributes as opposed to an XML file (`GenerateDocumentationFile`).</Description>
    <PackageTags>Documentation;Docs;Xml;DocsXml;Reflection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="RhoMicro.CodeAnalysis.Lyra">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="RhoMicro.CodeAnalysis.UtilityGenerators"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\RhoMicro.Staple\XmlDocumentationAttribute.cs">
      <Link>XmlDocumentationAttribute.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    <None Include="../README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always"/>
  </ItemGroup>

</Project>
