<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>RhoMicro.Staple</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RhoMicro.Staple.Analyzers\RhoMicro.Staple.Analyzers.csproj" OutputItemType="analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.HashCode"/>
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="RhoMicro.CodeAnalysis.Janus"/>
    <PackageReference Include="System.Collections.Immutable"/>
    <PackageReference Include="System.Memory"/>
  </ItemGroup>

</Project>
